from datetime import datetime

def traceError (function, error):
  print(datetime.now().time(), datetime.now().date(), function, error)

def userAction (user):
  pass
